### ISSUE TITLE
Stratégie de déploiement - décembre 2020

### ISSUE THREAD

**Issue by DavidBruant** [betagouv/azur.comobi.fr#41]
Suite à la session d'aujourd'hui avec @AudreyBramy 

On a bloqué sur #24, spécifiquement sur déployer sur Heroku

En l'état de la PR, heroku s'arrête parce qu'il ne trouve pas le binaire `jekyll` pour builder.
On a les solutions suivantes : 
1. Installer Ruby/Jekyll sur heroku avant de démarrer le binaire `jekyll`
    - ça complique un peu la stack 
2. Installer docker et lancer une image jekyll pour builder 
    - on va avoir besoin de docker bientôt de toutes les manières (mais ptèt qu'Heroku nous complique la vie parce qu'attend plutôt un container à déployer qu'un container pour builder)
3. Déployer le front-end sur github pages et le back-end sur Heroku
    - ça nous enlève le poids de gérer Jekyll pour le moment
    - ça découpe l'appli en 2 et on doit réconcilier les 2 morceaux avec de la configuration (pour que le front sache comment contacter le back) pour le moment
4. Build via une github action (créer une branche où est commité le `_site`) et déployer sur Heroku

**Comment by AudreyBramy** [comment]
On a utilisé la solution 4.
Le déploiement se fait sur la branche heroku.
